repos:
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.2
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.770
    hooks:
      - id: mypy

  # - repo: local
  #   hooks:
  #     - id: pytest
  #       name: pytest
  #       entry:  venv/bin/pytest -vvv
  #       language: script
  #       pass_filenames: false
  #       # alternative you could `types: [python] so it only runs when python files change`
  #       # though tests might be invalidated if you were to say change a data file
  #       always_run: true
  #       stages: [commit, push]
